version: '3.8'

services:
  postgres:
      image: postgres:15-alpine
      restart: always
      ports:
        - 5432:5432
      volumes:
        - db:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_DB=chi-orders
      healthcheck:
        test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d chi-orders'"]
        interval: 10s
        timeout: 3s
        retries: 3

  animal-repo:
    build: '.'
    ports:
      - 80:8082
    container_name: animal-repo
    volumes:
      - animal-volume:/var/images
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=chi-orders

volumes:
  db: